insert into user_details(id,birth_date,name) values(10001,current_date(),'Tom')
insert into user_details(id,birth_date,name) values(10002,current_date(),'Harry')
insert into user_details(id,birth_date,name) values(10003,current_date(),'Rosie')
insert into user_details(id,birth_date,name) values(10005,current_date(),'Maria')
insert into user_details(id,birth_date,name) values(10007,current_date(),'Andy')