insert into user_details(id,birth_date,name) values(10001,current_date(),'Tom')
insert into user_details(id,birth_date,name) values(10002,current_date(),'Harry')
insert into user_details(id,birth_date,name) values(10003,current_date(),'Rosie')
insert into user_details(id,birth_date,name) values(10005,current_date(),'Maria')
insert into user_details(id,birth_date,name) values(10007,current_date(),'Andy')

insert into post(id,description,user_id) values(20001,'I Want to learn Microservoces',10001)
insert into post(id,description,user_id) values(20002,'I Want to learn DevOps',10001)
insert into post(id,description,user_id) values(20003,'I Want to Get AWS Certified',10002)
insert into post(id,description,user_id) values(20004,'I Want to learn Multi Cloud',10002)